services:
  postgres-db:
    container_name: postgres-db
    image: postgres:16.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - ./db:/docker-entrypoint-initdb.d